---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
```

#Uploading the Data
```{r}
Crimes <- read.csv("../Data/Crime_Data_from_2020_to_Present.csv")
```

#Selecting for data columns of interest
```{r}
Crimes2 <- Crimes %>% select(c(DATE.OCC, AREA.NAME, Crm.Cd.Desc))
```

#Summarizing how often crime occurred (measured by day)
```{r}
Crimes2.summary <- Crimes2 %>% group_by(DATE.OCC, AREA.NAME,Crm.Cd.Desc) %>% summarise(CrimeCount = n())
```

#Creating substring to format dates in order
```{r}
Crimes2$Date <- substr(Crimes2$DATE.OCC, 1, 10)
```

#Creating a date that R can interpret
```{r}
Crimes2$Date <- as.Date(Crimes2$Date, "%m/%d/%Y")
```

#Creating "Year" as our variable
```{r}
Crimes2$Year <- as.numeric(format(Crimes2$Date, "%Y"))
```

```{r}
Crimes2$Year2 <- substr(Crimes2$DATE.OCC, 7, 10)
```

#Selecting for all characters that are related to "Theft"
```{r}
Crimes2$Theft <- grepl("Theft", Crimes2$Crm.Cd.Desc, ignore.case = TRUE)
```

```{r}
Crimes2.summary <- Crimes2 %>% group_by(Year2, AREA.NAME,Theft) %>% summarise(CrimeCount = n())
```

```{r}

```

